accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/details/', views.profile_details, name='profile_details'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
    path('payment/list/', views.payment_list, name='payment_list'),
    path('payment/create/', views.payment_create, name='payment_create'),
]

cinema/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ticketing/', include('ticketing.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import RegexValidator
from enum import Enum

class GenderChoices(Enum):
    MALE = 1
    FEMALE = 2

class Profile(models.Model):
    """
    Represents a user's profile.
    """

    class Meta:
        verbose_name = 'نمایه کاربری'
        verbose_name_plural = 'نمایه کاربری'

    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='حساب کاربری')
    mobile = models.CharField('تلفن همراه', max_length=11, validators=[RegexValidator(regex=r'^\d{11}$', message='Invalid mobile number')])
    gender = models.IntegerField('جنسیت', choices=[(gender.value, gender.name) for gender in GenderChoices], null=True, blank=True)
    birth_date = models.DateField('تاریخ تولد', null=True, blank=True)
    address = models.TextField('آدرس', null=True, blank=True)
    profile_image = models.ImageField('تصویر', upload_to='users/profile_images/', null=True, blank=True, default='users/profile_images/default.jpg')
    balance = models.IntegerField('اعتبار', default=0)

    def __str__(self):
        return self.user.get_full_name() or "User Profile"

    def get_balance_display(self):
        return '{} تومان'.format(self.balance)

    # behaviors
    def deposit(self, amount):
        with transaction.atomic():
            self.balance += amount
            self.save()

    def spend(self, amount):
        if self.balance < amount:
            return False
        with transaction.atomic():
            self.balance -= amount
            self.save()
        return True

class Payment(models.Model):
    """
    Represents a payment done by a user.
    """

    class Meta:
        verbose_name = 'پرداخت'
        verbose_name_plural = 'پرداخت'

    profile = models.ForeignKey('Profile', on_delete=models.CASCADE, verbose_name='کاربر')
    amount = models.PositiveIntegerField('مبلغ')
    transaction_time = models.DateTimeField('زمان تراکنش', auto_now_add=True)
    transaction_code = models.CharField('رسید تراکنش', max_length=30)

    def __str__(self):
        return '{} تومان افزایش اعتبار برای {}'.format(self.amount, self.profile)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.core.exceptions import ValidationError

from accounts.models import Payment, Profile

class PaymentForm(forms.ModelForm):
    """
    Form for handling Payment model.
    """
    class Meta:
        model = Payment
        fields = ['amount', 'transaction_code']
        # or: exclude = ['profile', 'transaction_time']

    def clean_transaction_code(self):
        """
        Validates the format of the transaction code.
        """
        code = self.cleaned_data.get('transaction_code')
        try:
            # should be in format: bank-<amount>-<TOKEN>#
            # e.g. bank-30000-UHB454GRH73BDYU#
            assert code.startswith('bank-')
            assert code.endswith('#')
            int(code.split('-')[1])
        except (AssertionError, ValueError, IndexError):
            raise ValidationError('قالب رسید تراکنش معتبر نیست')
        return code

    def clean_amount(self):
        """
        Validates that the amount is a multiple of 1000.
        """
        amount = self.cleaned_data.get('amount')
        if amount % 1000 != 0:
            raise ValidationError('مبلغ پرداختی باید ضریبی از هزار تومان باشد')
        return amount

    def clean(self):
        """
        Validates that the transaction code and amount match.
        """
        super().clean()
        code = self.cleaned_data.get('transaction_code')
        amount = self.cleaned_data.get('amount')
        if code and amount:
            try:
                if int(code.split('-')[1]) != amount:
                    raise ValidationError('رسید و مبلغ تراکنش هم‌خوانی ندارند')
            except (ValueError, IndexError):
                raise ValidationError('رسید و مبلغ تراکنش هم‌خوانی ندارند')


class MyUserForm(UserChangeForm):
    """
    Custom form for updating user information.
    """
    class Meta(UserChangeForm.Meta):
        fields = ['first_name', 'last_name', 'email']
    password = None


class ProfileForm(forms.ModelForm):
    """
    Form for handling Profile model.
    """
    class Meta:
        model = Profile
        fields = ['mobile', 'gender', 'address', 'profile_image']

accounts/views.py
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse
from accounts.forms import PaymentForm, ProfileForm, MyUserForm
from accounts.models import Payment

def login_view(request):
    next_url = request.GET.get('next')
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            redirect_url = next_url if next_url else reverse('ticketing:showtime_list')
            return redirect(redirect_url)
        else:
            context = {
                'username': username,
                'error': 'کاربری با این مشخصات یافت نشد'
            }
    return render(request, 'accounts/login.html', context)

def logout_view(request):
    logout(request)
    return redirect('accounts:login')

@login_required
def profile_details(request):
    if hasattr(request.user, 'profile'):
        profile = request.user.profile
        context = {
            'profile': profile
        }
        return render(request, 'accounts/profile_details.html', context)
    else:
        return redirect('accounts:profile_edit')

@login_required
def payment_list(request):
    payments = Payment.objects.filter(profile=request.user.profile).order_by('-transaction_time')
    context = {
        'payments': payments
    }
    return render(request, 'accounts/payment_list.html', context)

@login_required
def payment_create(request):
    if request.method == 'POST':
        payment_form = PaymentForm(request.POST)
        if payment_form.is_valid():
            payment = payment_form.save(commit=False)
            payment.profile = request.user.profile
            payment.save()
            request.user.profile.deposit(payment.amount)
            return redirect('accounts:payment_list')
    else:
        payment_form = PaymentForm()
    context = {
        'payment_form': payment_form
    }
    return render(request, 'accounts/payment_create.html', context)

@login_required
def profile_edit(request):
    if request.method == 'POST':
        user_form = MyUserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, files=request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('accounts:profile_details')
    else:
        user_form = MyUserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    context = {
        'user_form': user_form,
        'profile_form': profile_form
    }
    return render(request, 'accounts/profile_edit.html', context)

accounts/templates/accounts/base_accounts.html
{% extends "ticketing/base_page.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static "accounts/css/accounts.css" %}">
{% endblock %}

accounts/templates/accounts/login.html
{% extends "accounts/base_accounts.html" %}
{% load static %}

{% block title %}ورود کاربران{% endblock %}

{% block toolbar_title %}
    <i class="fas fa-user"></i>
    ورود کاربران
{% endblock %}

{% block main_content %}
    <form action="" method="post" class="login-form" novalidate>
        {% csrf_token %}
        {% if error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endif %}
        <div class="form-group row">
            <label for="username" class="col-3">نام کاربری:</label>
            <input id="username" class="col-9 form-control" type="text" name="username" value="{{ username }}" aria-label="Username" required />
        </div>
        <div class="form-group row">
            <label for="password" class="col-3">گذرواژه:</label>
            <input id="password" class="col-9 form-control" type="password" name="password" aria-label="Password" autocomplete="off" required />
        </div>
        <div class="form-group row justify-content-center">
            <div class="col-4">
                <button type="submit" class="btn btn-success w-100" aria-label="Login">
                    ورود
                </button>
            </div>
        </div>
    </form>
{% endblock %}

accounts/templates/accounts/payment_create.html
{% extends "accounts/base_accounts.html" %}
{% load static %}

{% block title %}
    پرداخت جدید
{% endblock %}

{% block toolbar_title %}
    <i class="fas fa-plus"></i>
    پرداخت جدید
{% endblock %}

{% block main_content %}
    <form action="" method="post" class="form py-2" novalidate>
        {% csrf_token %}
        <table class="my-1">
        {{ payment_form.as_table }}
        </table>
        <button type="submit" class="btn btn-success btn-sm">
            ثبت
        </button>
    </form>
    <!-- Success and error message placeholders -->
    <div id="form-messages" role="alert" aria-live="assertive"></div>
{% endblock %}

accounts/templates/accounts/payment_list.html
{% extends "accounts/base_accounts.html" %}
{% load static %}

{% block title %}
    پرداخت‌های من
{% endblock %}

{% block toolbar_title %}
    <i class="fas fa-receipt" aria-hidden="true"></i>
    پرداخت‌های من
{% endblock %}

{% block main_content %}
    <div class="row">
        <div class="col-12 mt-2">
            <a href="{% url "accounts:payment_create" %}" class="btn btn-success btn-sm" aria-label="Create new payment">
                <i class="fas fa-plus" aria-hidden="true"></i>
                پرداخت جدید
            </a>
        </div>
        <div class="col py-3">
            {% if payments %}
                <ul class="item-list">
                    {% for payment in payments %}
                        <li>
                            <span class="ml-4">
                                <span class="text-muted ml-1">مبلغ:</span>
                                {{ payment.amount }} تومان
                            </span>
                            <span class="ml-4">
                                <span class="text-muted ml-1">تاریخ تراکنش:</span>
                                {{ payment.transaction_time|date:"Y/n/j - H:i" }}
                            </span>
                            <span class="ml-4">
                                <span class="text-muted ml-1">رسید تراکنش:</span>
                                {{ payment.transaction_code }}
                            </span>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <div class="alert alert-danger" role="alert">
                    هیچ تراکنشی برای نمایش وجود ندارد.
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/profile_details.html
{% extends "accounts/base_accounts.html" %}
{% load static %}

{% block title %}{{ profile }}{% endblock %}

{% block toolbar_title %}
    <i class="fas fa-user"></i>
    مشاهده نمایه
{% endblock %}

{% block main_content %}
    <section class="row py-3">
        <div class="col-8 profile-details">
            <div class="row px-3">
                <div class="col-4">
                    <small class="text-muted">
                        <i class="far fa-user"></i>
                        نام کاربری:
                    </small>
                </div>
                <div class="col-8">
                    {{ user.username }}
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-4">
                    <small class="text-muted">
                        <i class="far fa-address-card"></i>
                        نام و نام خانوادگی:
                    </small>
                </div>
                <div class="col-8">
                    {{ profile.user.get_full_name }}
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-4">
                    <small class="text-muted">
                        <i class="fas fa-birthday-cake"></i>
                        تاریخ تولد:
                    </small>
                </div>
                <div class="col-8">
                    {{ profile.birth_date|date:"Y/n/j" }}
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-4">
                    <small class="text-muted">
                        <i class="fas fa-mobile-alt"></i>
                        تلفن همراه:
                    </small>
                </div>
                <div class="col-8">
                    {{ profile.mobile }}
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-4">
                    <small class="text-muted">
                        <i class="fas fa-coins"></i>
                        اعتبار:
                    </small>
                </div>
                <div class="col-4">
                    {{ profile.get_balance_display }}
                </div>
                <div class="col-4 text-left">
                    <a class="btn btn-xs btn-success my-1" href="{% url "accounts:payment_create" %}">
                        <i class="fas fa-plus"></i>
                        افزایش اعتبار
                    </a>
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-2">
                    <small class="text-muted">
                        <i class="fas fa-home"></i>
                        آدرس:
                    </small>
                </div>
                <div class="col-10 item-text-box">
                    {{ profile.address }}
                </div>
            </div>
        </div>
        <div class="col-4 text-center">
            {% if profile.profile_image %}
                <figure>
                    <img class="profile-image" src="{{ profile.profile_image.url }}" alt="{{ profile }}">
                </figure>
            {% endif %}
            <div class="profile-buttons mt-4">
                <a class="btn btn-secondary" href="{% url "accounts:profile_edit" %}" aria-label="Edit Profile">
                    <i class="fas fa-edit"></i>
                    ویرایش نمایه
                </a>
                <a class="btn btn-warning" href="#" aria-label="Change Password">
                    <i class="fas fa-key"></i>
                    تغییر گذرواژه
                </a>
            </div>
        </div>
    </section>
{% endblock %}

accounts/templates/accounts/profile_edit.html
{% extends "accounts/base_accounts.html" %}
{% load static %}

{% block title %}
    ویرایش نمایه
{% endblock %}

{% block toolbar_title %}
    <i class="fas fa-edit"></i>
    ویرایش نمایه
{% endblock %}

{% block main_content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row py-3">
            <div class="col-10 item-details profile-items">
                <div class="row px-3">
                    <div class="col-2">
                        <label for="username" class="text-muted">
                            <i class="far fa-user"></i>
                            نام کاربری:
                        </label>
                    </div>
                    <div class="col-4">
                        {{ user.username }}
                    </div>
                    <div class="col-2 pl-0">
                        <label for="gender" class="text-muted">
                            <i class="far fa-clock"></i>
                            جنسیت:
                        </label>
                    </div>
                    <div class="col-4">
                        {{ profile_form.gender }}
                    </div>
                    <div class="w-100 my-1"></div>
                    <div class="col-2">
                        <label for="first_name" class="text-muted">
                            <i class="far fa-address-card"></i>
                            نام:
                        </label>
                    </div>
                    <div class="col-4">
                        {{ user_form.first_name }}
                    </div>
                    <div class="col-2 pl-0">
                        <label for="last_name" class="text-muted">
                            <i class="far fa-address-card"></i>
                            نام خانوادگی:
                        </label>
                    </div>
                    <div class="col-4">
                        {{ user_form.last_name }}
                    </div>
                    <div class="w-100 my-1"></div>
                    <div class="col-2">
                        <label for="email" class="text-muted">
                            <i class="far fa-envelope-open"></i>
                            ایمیل:
                        </label>
                    </div>
                    <div class="col-4">
                        {{ user_form.email }}
                    </div>
                    <div class="col-2 pl-0">
                        <label for="mobile" class="text-muted">
                            <i class="fas fa-mobile-alt"></i>
                            تلفن همراه:
                        </label>
                    </div>
                    <div class="col-4">
                        {{ profile_form.mobile }}
                    </div>
                    <div class="w-100 my-1"></div>
                    <div class="col-2">
                        <label for="address" class="text-muted">
                            <i class="fas fa-home"></i>
                            آدرس:
                        </label>
                    </div>
                    <div class="col-10 item-text-box">
                        {{ profile_form.address }}
                    </div>
                    <div class="w-100 my-1"></div>
                    <button type="submit" class="btn btn-primary btn-sm">
                        ذخیره
                    </button>
                </div>
            </div>
            <div class="col-2 pr-0 text-center">
                {% if user.profile.profile_image %}
                    <img class="profile-image" src="{{ user.profile.profile_image.url }}" alt="{{ user.profile }}">
                {% endif %}
                <button type="button" class="btn btn-warning btn-sm mt-2"
                        data-toggle="modal" data-target="#profile-image-modal">
                    <i class="fas fa-image"></i>
                </button>
                <div class="modal fade" id="profile-image-modal">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-body">
                                {{ profile_form.profile_image }}
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}