accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/details/', views.profile_details, name='profile_details'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
    path('payment/list/', views.payment_list, name='payment_list'),
    path('payment/create/', views.payment_create, name='payment_create'),
]

cinema/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ticketing/', include('ticketing.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticketing/urls.py
from django.urls import path

from . import views

app_name = 'ticketing'
urlpatterns = [
    path('movie/list/', views.movie_list, name='movie_list'),
    path('movie/details/<int:movie_id>/', views.movie_details, name='movie_details'),
    path('cinema/list/', views.cinema_list, name='cinema_list'),
    path('cinema/details/<int:cinema_id>/', views.cinema_details, name='cinema_details'),
    path('showtime/list/', views.showtime_list, name='showtime_list'),
    path('showtime/details/<int:showtime_id>/', views.showtime_details, name='showtime_details'),
    path('ticket/list/', views.ticket_list, name='ticket_list'),
    path('ticket/details/<int:ticket_id>/', views.ticket_details, name='ticket_details'),
]

ticketing/models.py
from django.db import models


class Movie(models.Model):
    """
    Represents a movie
    """

    class Meta:
        verbose_name = 'فیلم'
        verbose_name_plural = 'فیلم'

    name = models.CharField('عنوان', max_length=100)
    director = models.CharField('کارگردان', max_length=50)
    year = models.IntegerField('سال تولید')
    length = models.IntegerField('مدت زمان')
    description = models.TextField('توضیح فیلم')
    poster = models.ImageField('پوستر', upload_to='movie_posters/')

    def __str__(self):
        return self.name


class Cinema(models.Model):
    """
    Represents a cinema (movie theater)
    """

    class Meta:
        verbose_name = 'سینما'
        verbose_name_plural = 'سینما'

    name = models.CharField('نام', max_length=50)
    city = models.CharField('شهر', max_length=30, default='تهران')
    capacity = models.IntegerField('گنجایش')
    phone = models.CharField('تلفن', max_length=30, blank=True)
    address = models.TextField('آدرس')
    image = models.ImageField('تصویر', upload_to='cinema_images/', null=True)

    def __str__(self):
        return self.name


class ShowTime(models.Model):
    """
    Represents a movie show in a cinema at a specific time
    """

    class Meta:
        verbose_name = 'سانس'
        verbose_name_plural = 'سانس'

    # read more about on_delete from
    # https://docs.djangoproject.com/en/2.2/ref/models/fields/#django.db.models.ForeignKey.on_delete
    # choices are PROTECT, CASCADE, SET_NULL, SET_DEFAULT, SET(), DO_NOTHING
    movie = models.ForeignKey('Movie', on_delete=models.PROTECT, verbose_name='فیلم')
    cinema = models.ForeignKey('Cinema', on_delete=models.PROTECT, verbose_name='سینما')

    start_time = models.DateTimeField('زمان شروع نمایش')
    price = models.IntegerField('قیمت')
    salable_seats = models.IntegerField('صندلی‌های قابل فروش')
    free_seats = models.IntegerField('صندلی‌های خالی')

    SALE_NOT_STARTED = 1
    SALE_OPEN = 2
    TICKETS_SOLD = 3
    SALE_CLOSED = 4
    MOVIE_PLAYED = 5
    SHOW_CANCELED = 6
    status_choices = (
        (SALE_NOT_STARTED, 'فروش آغاز نشده'),
        (SALE_OPEN, 'در حال فروش بلیت'),
        (TICKETS_SOLD, 'بلیت‌ها تمام شد'),
        (SALE_CLOSED, 'فروش بلیت بسته شد'),
        (MOVIE_PLAYED, 'فیلم پخش شد'),
        (SHOW_CANCELED, 'سانس لغو شد'),
    )
    status = models.IntegerField('وضعیت', choices=status_choices, default=SALE_NOT_STARTED)

    def __str__(self):
        return '{} - {} - {}'.format(self.movie, self.cinema, self.start_time)

    def get_price_display(self):
        return '{} تومان'.format(self.price)

    def is_full(self):
        """
        Returns True if all seats are sold
        """
        return self.free_seats == 0

    def open_sale(self):
        """
        Opens ticket sale
        If sale was opened before, raises an exception
        """
        if self.status == ShowTime.SALE_NOT_STARTED:
            self.status = ShowTime.SALE_OPEN
            self.save()
        else:
            raise Exception('Sale has been started before')

    def close_sale(self):
        """
        Closes ticket sale
        If sale is not open, raises an exception
        """
        if self.status == ShowTime.SALE_OPEN:
            self.status = ShowTime.SALE_CLOSED
            self.save()
        else:
            raise Exception('Sale is not open')

    def expire_showtime(self, is_canceled=False):
        """
        Expires showtime and updates the status
        :param is_canceled: A boolean indicating whether the show is canceled or not, default is False
        """
        if self.status not in (ShowTime.MOVIE_PLAYED, ShowTime.SHOW_CANCELED):
            self.status = ShowTime.SHOW_CANCELED if is_canceled else ShowTime.MOVIE_PLAYED
            self.save()
        else:
            raise Exception('Show has been expired before')

    def reserve_seats(self, seat_count):
        """
        Reserves one or more seats for a customer
        :param seat_count: An integer as the number of seats to be reserved
        """
        assert isinstance(seat_count, int) and seat_count > 0, 'Number of seats should be a positive integer'
        assert self.status == ShowTime.SALE_OPEN, 'Sale is not open'
        assert self.free_seats >= seat_count, 'Not enough free seats'
        self.free_seats -= seat_count
        if self.free_seats == 0:
            self.status = ShowTime.TICKETS_SOLD
        self.save()


class Ticket(models.Model):
    """
    Represents one or more tickets, bought by a user in an order
    """

    class Meta:
        verbose_name = 'بلیت'
        verbose_name_plural = 'بلیت'

    showtime = models.ForeignKey('ShowTime', on_delete=models.PROTECT, verbose_name='سانس')
    customer = models.ForeignKey('accounts.Profile', on_delete=models.PROTECT, verbose_name='خریدار')
    seat_count = models.IntegerField('تعداد صندلی')
    order_time = models.DateTimeField('زمان خرید', auto_now_add=True)

    def __str__(self):
        return "{} بلیت به نام {} برای فیلم {}".format(self.seat_count, self.customer, self.showtime.movie)

ticketing/forms.py
from django import forms

from ticketing.models import Cinema


class ShowTimeSearchForm(forms.Form):
    PRICE_ANY = '0'
    PRICE_UNDER_10 = '1'
    PRICE_10_TO_15 = '2'
    PRICE_15_TO_20 = '3'
    PRICE_ABOVE_20 = '4'
    PRICE_LEVEL_CHOICES = (
        (PRICE_ANY, 'هر قیمتی'),
        (PRICE_UNDER_10, 'تا ۱۰ هزار تومان'),
        (PRICE_10_TO_15, '۱۰ تا ۱۵ هزار تومان'),
        (PRICE_15_TO_20, '۱۵ تا ۲۰ هزار تومان'),
        (PRICE_ABOVE_20, 'بیش از ۲۰ هزار تومان'),
    )

    movie_name = forms.CharField(label='عنوان فیلم', max_length=100, required=False)
    sale_is_open = forms.BooleanField(label='فقط سانس‌های قابل خرید', required=False)
    movie_length_min = forms.IntegerField(label='حداقل زمان فیلم', min_value=0, max_value=200, required=False)
    movie_length_max = forms.IntegerField(label='حداکثر زمان فیلم', min_value=0, max_value=200, required=False)
    cinema = forms.ModelChoiceField(label='سینما', required=False, queryset=Cinema.objects.all())
    price_level = forms.ChoiceField(label='محدوده قیمت', choices=PRICE_LEVEL_CHOICES, required=False)

    def get_price_boundries(self):
        price_level = self.cleaned_data['price_level']
        if price_level == ShowTimeSearchForm.PRICE_UNDER_10:
            return None, 10000
        elif price_level == ShowTimeSearchForm.PRICE_10_TO_15:
            return 10000, 15000
        elif price_level == ShowTimeSearchForm.PRICE_15_TO_20:
            return 15000, 20000
        elif price_level == ShowTimeSearchForm.PRICE_ABOVE_20:
            return 20000, None
        else:
            return None, None

ticketing/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from ticketing.forms import ShowTimeSearchForm
from .models import Movie, Cinema, ShowTime, Ticket


def movie_list(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies
    }
    return render(request, 'ticketing/movie_list.html', context)


def cinema_list(request):
    cinemas = Cinema.objects.all()
    context = {
        'cinemas': cinemas
    }
    return render(request, 'ticketing/cinema_list.html', context)


def movie_details(request, movie_id):
    movie = Movie.objects.get(pk=movie_id)
    context = {
        'movie': movie
    }
    return render(request, 'ticketing/movie_details.html', context)


def cinema_details(request, cinema_id):
    cinema = Cinema.objects.get(pk=cinema_id)
    context = {
        'cinema': cinema
    }
    return render(request, 'ticketing/cinema_details.html', context)


def showtime_list(request):
    showtimes = ShowTime.objects.all()
    search_form = ShowTimeSearchForm(request.GET)
    if search_form.is_valid():
        showtimes = showtimes.filter(movie__name__contains=search_form.cleaned_data['movie_name'])
        if search_form.cleaned_data['sale_is_open']:
            showtimes = showtimes.filter(status=ShowTime.SALE_OPEN)
        if search_form.cleaned_data['movie_length_min'] is not None:
            showtimes = showtimes.filter(movie__length__gte=search_form.cleaned_data['movie_length_min'])
        if search_form.cleaned_data['movie_length_max'] is not None:
            showtimes = showtimes.filter(movie__length__lte=search_form.cleaned_data['movie_length_max'])
        if search_form.cleaned_data['cinema'] is not None:
            showtimes = showtimes.filter(cinema=search_form.cleaned_data['cinema'])
        min_price, max_price = search_form.get_price_boundries()
        if min_price is not None:
            showtimes = showtimes.filter(price__gt=min_price)
        if max_price is not None:
            showtimes = showtimes.filter(price__lte=max_price)
    showtimes = showtimes.order_by('start_time')
    context = {
        'showtimes': showtimes,
        'search_form': search_form
    }
    return render(request, 'ticketing/showtime_list.html', context)


@login_required
def showtime_details(request, showtime_id):
    showtime = ShowTime.objects.get(pk=showtime_id)
    context = {
        'showtime': showtime
    }
    if request.method == 'POST':
        try:
            seat_count = int(request.POST['seat_count'])
            assert showtime.status == showtime.SALE_OPEN, 'فروش بلیت برای این سانس ممکن نیست.'
            assert showtime.free_seats >= seat_count, 'این سانس به اندازه کافی صندلی خالی ندارد.'
            price = showtime.price * seat_count
            assert request.user.profile.spend(price), 'اعتبار شما برای خرید بلیت کافی نیست.'
            showtime.reserve_seats(seat_count)
            ticket = Ticket.objects.create(showtime=showtime, customer=request.user.profile, seat_count=seat_count)
        except Exception as e:
            context['error'] = str(e)
        else:
            return HttpResponseRedirect(reverse('ticketing:ticket_details', kwargs={'ticket_id': ticket.id}))
    return render(request, 'ticketing/showtime_details.html', context)


@login_required
def ticket_list(request):
    tickets = Ticket.objects.filter(customer=request.user.profile).order_by('-order_time')
    context = {
        'tickets': tickets
    }
    return render(request, 'ticketing/ticket_list.html', context)


@login_required
def ticket_details(request, ticket_id):
    ticket = Ticket.objects.get(pk=ticket_id)
    context = {
        'ticket': ticket
    }
    return render(request, 'ticketing/ticket_details.html', context)

ticketing/templates/ticketing/base_page.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block extra_headers %}{% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static "ticketing/css/bootstrap.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "ticketing/css/font-awesome.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "ticketing/css/main.css" %}">
    {% block extra_css %}{% endblock %}
</head>
<body dir="rtl">
<div class="container" id="container">
    <div class="row align-items-center" id="header">
        <div class="col text-center">
            <h2>
                سامانه فروش بلیت سینما
            </h2>
        </div>
    </div>
    <div class="row align-items-center" id="toolbar">
        <div class="col-6">
            <h4>
                {% block toolbar_title %}{% endblock %}
            </h4>
        </div>
        <div class="col-6 text-left">
            {% block toolbar_buttons %}
                <a class="btn btn-light py-1 px-2" href="{% url "ticketing:movie_list" %}">
                    <i class="fas fa-film"></i>
                    فیلم‌ها
                </a>
                <a class="btn btn-light py-1 px-2" href="{% url "ticketing:cinema_list" %}">
                    <i class="fas fa-building"></i>
                    سینماها
                </a>
                <a class="btn btn-success py-1 px-2" href="{% url "ticketing:showtime_list" %}">
                    <i class="fas fa-ticket-alt"></i>
                    خرید بلیت
                </a>
            {% endblock %}
            {% block user_button %}
                {% if user.is_authenticated %}
                    <div class="dropdown">
                        <a class="btn btn-primary dropdown-toggle py-1 px-2" id="user-button" href="#"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-user"></i>
                            {{ user.get_full_name }}
                        </a>
                        <div class="dropdown-menu text-right" aria-labelledby="user-button" dir="rtl">
                            <span class="dropdown-item-text">
                                <i class="fas fa-coins"></i>
                                اعتبار:
                                {{ user.profile.balance }}
                                تومان
                            </span>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url "accounts:profile_details" %}">
                                <i class="far fa-address-card"></i>
                                نمایه کاربری
                            </a>
                            <a class="dropdown-item" href="{% url "ticketing:ticket_list" %}">
                                <i class="fas fa-ticket-alt"></i>
                                بلیت‌های من
                            </a>
                            <a class="dropdown-item" href="{% url "accounts:payment_list" %}">
                                <i class="fas fa-receipt"></i>
                                پرداخت‌های من
                            </a>
                            <a class="dropdown-item" href="{% url "accounts:logout" %}">
                                <i class="fas fa-sign-out-alt"></i>
                                خروج
                            </a>
                        </div>
                    </div>
                {% else %}
                    <a class="btn btn-primary py-1 px-2 mr-3" href="{% url "accounts:login" %}">
                        <i class="fas fa-sign-in-alt"></i>
                        ورود
                    </a>
                {% endif %}
            {% endblock %}
        </div>
    </div>

    {% block main_content %}{% endblock %}

    <div class="row align-content-center" id="footer">
        <div class="col text-center">
            <span>
                ما را در شبکه‌های اجتماعی دنبال کنید.

                <a class="social-media-icon" href="https://facebook.com/#">
                    <i class="fab fa-facebook"></i>
                </a>
                <a class="social-media-icon" href="https://twitter.com/#">
                    <i class="fab fa-twitter"></i>
                </a>
                <a class="social-media-icon" href="https://instagram.com/#">
                    <i class="fab fa-instagram"></i>
                </a>
                <a class="social-media-icon" href="https://telegram.org/#">
                    <i class="fab fa-telegram-plane"></i>
                </a>
            </span>
        </div>
    </div>
</div>
<script src="{% static "ticketing/js/jquery-3.4.0.min.js" %}"></script>
<script src="{% static "ticketing/js/bootstrap.bundle.js" %}"></script>
<script src="{% static "ticketing/js/font-awesome.js" %}"></script>
<script src="{% static "ticketing/js/main.js" %}"></script>
{% block extra_js %}{% endblock %}
</body>
</html>

ticketing/templates/ticketing/cinema_details.html
{% extends "ticketing/base_page.html" %}
{% load static %}

{% block title %}{{ cinema.name }}{% endblock %}

{% block toolbar_title %}
    <i class="fas fa-building"></i>
    {{ cinema.name }}
{% endblock %}

{% block toolbar_buttons %}
    <a class="btn btn-warning py-1 px-2" href="{% url "ticketing:cinema_list" %}">
        <i class="fas fa-list"></i>
        فهرست سینماها
    </a>
{% endblock %}

{% block main_content %}
    <div class="row py-3">
        <div class="col-8 item-details">
            <div class="row px-3">
                <div class="col-3">
                    <small class="text-muted">
                        شهر:
                    </small>
                </div>
                <div class="col-9">
                    {% if cinema.city %}
                        {{ cinema.city }}
                    {% else %}
                        <small class="text-muted">(نامشخص)</small>
                    {% endif %}
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-3">
                    <small class="text-muted">
                        ظرفیت:
                    </small>
                </div>
                <div class="col-9">
                    {{ cinema.capacity }}
                    نفر
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-3">
                    <small class="text-muted">
                        تلفن:
                    </small>
                </div>
                <div class="col-9">
                    {{ cinema.phone|default:"-" }}
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-3">
                    <small class="text-muted">
                        آدرس:
                    </small>
                </div>
                <div class="col-9 item-text-box">
                    {{ cinema.address }}
                </div>
            </div>
        </div>
        <div class="col-4 text-center">
            {% if cinema.image %}
                <img class="item-image" src="{{ cinema.image.url }}" alt="{{ cinema.name }}">
            {% else %}
                <i class="far fa-10x fa-building text-muted"></i>
            {% endif %}
        </div>
    </div>
{% endblock %}

ticketing/templates/ticketing/cinema_list.html
{% extends "ticketing/base_page.html" %}
{% load static %}

{% block title %}
    فهرست سینماها
{% endblock %}

{% block toolbar_title %}
    فهرست سینماها
{% endblock %}

{% block main_content %}
    <div class="row">
        <div class="col py-3">
            {% if cinemas %}
                <ul class="item-list">
                    {% for cinema in cinemas %}
                        <li>
                            <a href="{% url "ticketing:cinema_details" cinema_id=cinema.id %}">
                                <i class="fas fa-building"></i>
                                {{ cinema }}
                                {% if cinema.city %}
                                    <small class="text-muted">
                                        ({{ cinema.city }})
                                    </small>
                                {% endif %}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <div class="alert alert-danger">
                    در حال حاضر هیچ سالنی برای نمایش وجود ندارد.
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

ticketing/templates/ticketing/movie_list.html
{% extends "ticketing/base_page.html" %}
{% load static %}

{% block title %}
    فهرست فیلم‌ها
{% endblock %}

{% block toolbar_title %}
    فهرست فیلم‌ها
{% endblock %}

{% block main_content %}
    <div class="row">
        <div class="col py-3">
            {% if movies %}
                <ul class="item-list">
                    {% for movie in movies %}
                        <li>
                            <a href="{% url "ticketing:movie_details" movie_id=movie.id %}">
                                <i class="fas fa-film"></i>
                                {{ movie }}
                                <small class="text-muted">
                                    ({{ movie.director }})
                                </small>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <div class="alert alert-danger">
                    در حال حاضر هیچ فیلمی برای نمایش وجود ندارد.
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

ticketing/templates/ticketing/showtime_details.html
{% extends "ticketing/base_page.html" %}
{% load static %}

{% block title %}
    خرید بلیت
    {{ showtime.movie.name }}
{% endblock %}

{% block toolbar_title %}
    <i class="fas fa-play-circle"></i>
    {{ showtime.movie.name }}
    <span class="small">
        ({{ showtime.start_time|date:"l ساعت H:i" }})
    </span>
{% endblock %}

{% block toolbar_buttons %}
    <a class="btn btn-warning py-1 px-2" href="{% url "ticketing:showtime_list" %}">
        <i class="fas fa-list"></i>
        فهرست سانس‌ها
    </a>
{% endblock %}

{% block main_content %}
    <div class="row py-3">
        <div class="col-8 item-details">
            <div class="row px-3">
                <div class="col-3">
                    <small class="text-muted">
                        <i class="fas fa-film"></i>
                        نام فیلم:
                    </small>
                </div>
                <div class="col-9">
                    {{ showtime.movie.name }}
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-3">
                    <small class="text-muted">
                        <i class="fas fa-building"></i>
                        نام سینما:
                    </small>
                </div>
                <div class="col-6">
                    {{ showtime.cinema.name }}
                </div>
                <div class="col-3 text-left">
                    {% if showtime.status == showtime.SALE_OPEN %}
                        <span class="badge
                            {% if showtime.free_seats < 10 %}
                                badge-danger
                            {% else %}
                                badge-info
                            {% endif %}">
                        {{ showtime.free_seats }}
                        صندلی مانده
                        </span>
                    {% else %}
                        <span class="badge badge-dark">
                            {{ showtime.get_status_display }}
                        <span>
                    {% endif %}
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-3">
                    <small class="text-muted">
                        <i class="far fa-clock"></i>
                        شروع سانس:
                    </small>
                </div>
                <div class="col-9">
                    {{ showtime.start_time|date:"l Y/n/j ساعت H:i" }}
                </div>
                <div class="w-100 my-1"></div>
                <div class="col-3">
                    <small class="text-muted">
                        <i class="fas fa-map-marker-alt"></i>
                        آدرس سینما:
                    </small>
                </div>
                <div class="col-9 item-text-box">
                    {{ showtime.cinema.address }}
                </div>
                {% if showtime.status == showtime.SALE_OPEN %}
                    <div class="w-100 my-1"></div>
                    <div class="col-3">
                        <small class="text-muted">
                            <i class="fas fa-money-bill-wave"></i>
                            قیمت بلیت:
                        </small>
                    </div>
                    <div class="col-4">
                        {{ showtime.price }}
                        تومان
                    </div>
                    <div class="col-5">
                    <form action="" method="post" class="form-inline">
                        {% csrf_token %}
                        <select name="seat_count" class="form-control form-control-sm ml-2">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                        </select>
                        <button type="submit" class="btn btn-xs btn-success my-1" href="#">
                            خرید بلیت
                        </button>
                    </form>
                    </div>
                {% endif %}
                {% if error %}
                    <div class="w-100 my-1"></div>
                    <span class="col-12 alert alert-danger align-items-baseline small p-2">
                        <i class="fas fa-exclamation-circle"></i>
                        {{ error }}
                    </span>
                {% endif %}
            </div>
        </div>
        <div class="col-4 text-center">
            <img class="item-image" src="{{ showtime.movie.poster.url }}" alt="{{ showtime.movie.name }}">
        </div>
    </div>
{% endblock %}

ticketing/templates/ticketing/showtime_list.html
{% extends "ticketing/base_page.html" %}
{% load static %}

{% block title %}
    سانس‌های نمایش
{% endblock %}

{% block toolbar_title %}
    فهرست سانس‌های نمایش
{% endblock %}

{% block main_content %}
    <div class="row">
        <div class="col py-3">
            <div class="row">
                <div class="col my-1 mx-3 py-2 px-3 search-bar">
                    <form action="" method="get" class="form-row px-2">
                        {% include "ticketing/_form_field.html" with field=search_form.movie_name %}
                        {% include "ticketing/_form_field.html" with field=search_form.cinema %}

                        {% include "ticketing/_form_field.html" with field=search_form.movie_length_min label_size=2 input_size=2 %}
                        {% include "ticketing/_form_field.html" with field=search_form.movie_length_max label_size=2 input_size=2 %}
                        <div class="col-4">
                            {{ search_form.sale_is_open }}
                            {{ search_form.sale_is_open.label }}
                        </div>
                        {% include "ticketing/_form_field.html" with field=search_form.price_level %}
                        <button type="submit" class="btn btn-primary btn-sm">
                            جست‌وجو
                        </button>
                    </form>
                </div>
            </div>
            {% if showtimes %}
                <div class="row px-2">
                    <div class="col">
                        <div class="alert alert-info mt-2 mb-0 py-1 px-3">
                            {{ showtimes.count }}
                            سانس یافت شد.
                        </div>
                    </div>
                </div>
                <div class="row px-2">
                    {% for showtime in showtimes %}
                        <div class="col-3 px-2 py-2">
                            <a href="{% url "ticketing:showtime_details" showtime_id=showtime.id %}"
                               class="showtime-box btn
                                {% if showtime.status != showtime.SALE_OPEN %}
                                    disabled btn-outline-secondary
                                {% else %}
                                    btn-outline-dark
                                {% endif %}">
                                <span>{{ showtime.movie }}</span>
                                <br/>
                                <span>{{ showtime.cinema }}</span>
                                <br/>
                                <span>
                                    {{ showtime.start_time|date:"l n/j ساعت H:i" }}
                                </span>
                                {# TODO: extract a template tag or filter for class below #}
                                <span class="showtime-status badge
                                    {% if showtime.status == showtime.SALE_NOT_STARTED %}
                                        badge-warning
                                    {% elif showtime.status == showtime.SHOW_CANCELED %}
                                        badge-danger
                                    {% elif showtime.status == showtime.SALE_OPEN %}
                                        badge-success
                                    {% else %}
                                        badge-secondary
                                    {% endif %}">
                                    {% if showtime.status == showtime.SALE_OPEN %}
                                        {{ showtime.get_price_display }}
                                    {% else %}
                                        {{ showtime.get_status_display }}
                                    {% endif %}
                                </span>
                                {% if showtime.status == showtime.SALE_OPEN and showtime.free_seats < 10 %}
                                    <span class="badge badge-danger">
                                    {{ showtime.free_seats }}
                                    صندلی
                                    </span>
                                {% endif %}
                            </a>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <div class="alert alert-danger">
                    در حال حاضر هیچ سانسی برای نمایش وجود ندارد.
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}